In [1]:
import torch

x = torch.tensor([0.1, 0.2, 0.3])
w_enc = torch.tensor([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]])
w_dec = torch.tensor([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])

In [4]:
torch.matmul(x, w_enc)

tensor([0.2200, 0.2800])

In [8]:
x @ w_enc

tensor([0.2200, 0.2800])

In [9]:
z = torch.sigmoid(torch.matmul(x, w_enc))
z

tensor([0.5548, 0.5695])

In [11]:
x_hat = torch.sigmoid(torch.matmul(z, w_dec))
x_hat

tensor([0.5704, 0.5977, 0.6244])

In [15]:
loss = torch.nn.MSELoss()(x_hat, x)
loss

tensor(0.1615)

dl_dw_dec = 2 . (x_hat - x) . z_transpose . x_hat . (1 - x_hat)

In [27]:
(x_hat * (1 - x_hat)).view(1,3)

tensor([[0.2451, 0.2405, 0.2345]])

In [28]:
torch.matmul(z.T.view(2,1), (x_hat * (1 - x_hat)).view(1,3))

tensor([[0.1359, 0.1334, 0.1301],
        [0.1396, 0.1370, 0.1336]])

In [30]:
2 * (x_hat - x)

tensor([0.9407, 0.7953, 0.6488])

In [32]:
dl_dw_dec = 2 * (x_hat - x) * torch.matmul(z.T.view(2,1), (x_hat * (1 - x_hat)).view(1,3))
dl_dw_dec

tensor([[0.1279, 0.1061, 0.0844],
        [0.1313, 0.1089, 0.0867]])

In [33]:
x_hat * (1 - x_hat)

tensor([0.2451, 0.2405, 0.2345])

In [35]:
z * (1 - z)

tensor([0.2470, 0.2452])

In [36]:
 w_dec.T

tensor([[0.1000, 0.4000],
        [0.2000, 0.5000],
        [0.3000, 0.6000]])

In [42]:
w_dec.T * z * (1 - z) 

tensor([[0.0247, 0.0981],
        [0.0494, 0.1226],
        [0.0741, 0.1471]])

In [49]:
x

tensor([0.1000, 0.2000, 0.3000])

In [44]:
x.T.vi * w_dec.T * z * (1 - z)


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [53]:
2 * (x_hat - x).view(1,3)

tensor([[0.9407, 0.7953, 0.6488]])

In [54]:
torch.matmul(2 * (x_hat - x).view(1,3), w_dec.T)

tensor([[0.4478, 1.1632]])

In [61]:
((x_hat * (1 - x_hat)) * x).view(3,1)

tensor([[0.0245],
        [0.0481],
        [0.0704]])

In [60]:
(z * (1 - z)).view(1,2)

tensor([[0.2470, 0.2452]])

In [62]:
torch.matmul(((x_hat * (1 - x_hat)) * x).view(3,1), (z * (1 - z)).view(1,2))

tensor([[0.0061, 0.0060],
        [0.0119, 0.0118],
        [0.0174, 0.0172]])

In [67]:
dl_dw_enc = torch.matmul(2 * (x_hat - x).view(1,3), w_dec.T) * torch.matmul(((x_hat * (1 - x_hat)) * x).view(3,1), (z * (1 - z)).view(1,2))

In [68]:
dl_dw_enc

tensor([[0.0027, 0.0070],
        [0.0053, 0.0137],
        [0.0078, 0.0201]])